import type { Owner, Property, StrataNotice, SyncLog } from '@/lib/definitions';

export const demoOwners: Array<Owner & { id: string }> = [
  {
    id: 'demo-owner-1',
    name: 'Ivy Chen & Leo Chen',
    email: 'ivy.chen@example.com',
    properties: ['EPS3494 Unit 1908', 'Harbour Heights - 3355 Binning Rd'],
    planCodes: ['EPS3494'],
    locatorCodes: ['B5263'],
    unitNumbers: ['1908'],
    propertyIds: ['demo-property-1'],
    source: 'buildium',
  },
  {
    id: 'demo-owner-2',
    name: 'Northlight Holdings Ltd.',
    email: null,
    properties: ['BCS3925 Unit 506', '18 W Cordova St'],
    planCodes: ['BCS3925'],
    locatorCodes: ['12-2-084'],
    unitNumbers: ['506'],
    propertyIds: ['demo-property-2'],
    source: 'buildium',
  },
  {
    id: 'demo-owner-3',
    name: 'Grace Park',
    email: 'grace.park@example.com',
    properties: ['EPS5421 Unit 702', '5987 Wilson Ave'],
    planCodes: ['EPS5421'],
    locatorCodes: ['B6012'],
    unitNumbers: ['702'],
    propertyIds: ['demo-property-3'],
    source: 'buildium',
  },
];

export const demoProperties: Property[] = [
  {
    id: 'demo-property-1',
    name: 'Harbour Heights',
    locator_code: 'B5263',
    owner_name: 'Ivy Chen & Leo Chen',
    address_1: '#1908-3355 Binning Rd',
    city: 'Vancouver',
    state: 'BC',
    postal_code: 'V6S 0J1',
    plan_code: 'EPS3494',
    unit_number: '1908',
  },
  {
    id: 'demo-property-2',
    name: 'Gastown Warehouse',
    locator_code: '12-2-084',
    owner_name: 'Northlight Holdings Ltd.',
    address_1: '#506-18 W Cordova St',
    city: 'Vancouver',
    state: 'BC',
    postal_code: 'V6B 0H2',
    plan_code: 'BCS3925',
    unit_number: '506',
  },
  {
    id: 'demo-property-3',
    name: 'Metro Point',
    locator_code: 'B6012',
    owner_name: 'Grace Park',
    address_1: '#702-5987 Wilson Ave',
    city: 'Burnaby',
    state: 'BC',
    postal_code: 'V5H 4R9',
    plan_code: 'EPS5421',
    unit_number: '702',
  },
  {
    id: 'demo-property-4',
    name: 'Address-only Example',
    locator_code: 'B7001',
    owner_name: 'Sample Owner Group',
    address_1: '#315-188 Keefer Pl',
    city: 'Vancouver',
    state: 'BC',
    postal_code: 'V6B 0J1',
    plan_code: null,
    unit_number: '315',
  },
];

export const demoNotices: StrataNotice[] = [
  {
    id: 'demo-notice-1',
    subject: 'EPS 3494 water shutdown on April 3',
    sender: 'buildingmanager@harbourheights.ca',
    receivedAt: '2026-03-29T17:30:00.000Z',
    content:
      'Please be advised that EPS 3494 will have a scheduled domestic water shutdown for stack maintenance on April 3 from 9:00 AM to 2:00 PM. Units 1901 to 1910 are directly impacted.',
    status: 'Ready',
    planCode: 'EPS3494',
    allPlanCodes: ['EPS3494'],
    aiSummary: {
      what: 'Scheduled domestic water shutdown for maintenance.',
      when: 'April 3 from 9:00 AM to 2:00 PM.',
      impact: 'High-rise residents in the affected stack will temporarily lose water service.',
      action: 'Owners should notify tenants in the impacted units and avoid water usage during the window.',
    },
    audience: {
      decision: 'TARGETED',
      confidence: 0.92,
      evidence: ['EPS 3494', 'Units 1901 to 1910 are directly impacted'],
      target_hints: {
        units: ['1908'],
        strata_lots: [],
        parking: [],
        locker: [],
      },
    },
    attachments: [
      {
        id: 'demo-attachment-1',
        filename: 'Water_Shutdown_Notice.pdf',
        contentType: 'application/pdf',
        size: 248392,
        isPdf: true,
        storagePath: null,
        localPath: null,
      },
    ],
    assignedOwnerId: 'demo-owner-1',
    assignedOwnerIds: ['demo-owner-1'],
    ownerMessage:
      '您好，Harbour Heights 管理处通知 4 月 3 日 9:00 AM 到 2:00 PM 会进行计划性停水，您名下 Unit 1908 属于受影响范围。建议尽快通知租客提前储水，并在施工时段避免用水。',
  },
  {
    id: 'demo-notice-2',
    subject: 'BCS3925 parkade gate repair update',
    sender: 'concierge@gastownwarehouse.com',
    receivedAt: '2026-03-28T20:15:00.000Z',
    content:
      'This is an update for BCS3925. The parkade gate motor will be replaced on Tuesday. Access may be intermittent for residents entering from Cordova Street.',
    status: 'Review',
    planCode: 'BCS3925',
    allPlanCodes: ['BCS3925'],
    aiSummary: {
      what: 'Parkade gate motor replacement.',
      when: 'Tuesday during daytime contractor hours.',
      impact: 'Vehicle access may be intermittent.',
      action: 'Confirm whether the disruption is broad enough to notify all owners or only affected residents.',
    },
    audience: {
      decision: 'REVIEW',
      confidence: 0.68,
      evidence: ['BCS3925', 'Access may be intermittent'],
      target_hints: {
        units: [],
        strata_lots: [],
        parking: ['parkade'],
        locker: [],
      },
    },
    attachments: [],
    assignedOwnerId: 'demo-owner-2',
    assignedOwnerIds: ['demo-owner-2'],
    ownerMessage:
      '您好，BCS3925 本周二将进行 parkade gate motor 更换，期间车辆进出可能间歇受影响。若您希望，我可以继续优化成适合发送给业主的正式通知版本。',
  },
  {
    id: 'demo-notice-3',
    subject: 'Fire alarm testing for EPS5421',
    sender: 'notices@metropointstrata.ca',
    receivedAt: '2026-03-27T18:00:00.000Z',
    content:
      'Annual fire alarm testing for EPS5421 is scheduled for Thursday, 10:00 AM to 4:00 PM. Technicians may require access to individual homes, including unit 702.',
    status: 'New',
    planCode: 'EPS5421',
    allPlanCodes: ['EPS5421'],
    aiSummary: null,
    audience: null,
    attachments: [],
    assignedOwnerId: null,
    assignedOwnerIds: null,
    ownerMessage: null,
  },
  {
    id: 'demo-notice-4',
    subject: 'Completed: lobby HVAC maintenance',
    sender: 'updates@harbourheights.ca',
    receivedAt: '2026-03-20T16:45:00.000Z',
    content:
      'Lobby HVAC servicing for EPS3494 has been completed. No further resident action is required.',
    status: 'Dispatched',
    planCode: 'EPS3494',
    allPlanCodes: ['EPS3494'],
    aiSummary: {
      what: 'Lobby HVAC servicing completed.',
      when: 'Completed on March 20.',
      impact: 'No action required.',
      action: 'Inform owners for awareness only.',
    },
    audience: {
      decision: 'BROADCAST',
      confidence: 0.85,
      evidence: ['No further resident action is required'],
      target_hints: {
        units: [],
        strata_lots: [],
        parking: [],
        locker: [],
      },
    },
    attachments: [],
    assignedOwnerId: 'demo-owner-1',
    assignedOwnerIds: ['demo-owner-1', 'demo-owner-3'],
    ownerMessage:
      '您好，大堂 HVAC maintenance 已完成，目前无需住户采取任何额外操作，仅供您留存备案。',
  },
];

export const demoSyncLogs: SyncLog[] = [
  {
    id: 'demo-sync-1',
    timestamp: '2026-03-29T22:20:07.000Z',
    window: 7,
    status: 'success',
    found: 18,
    inserted: 4,
    skipped: 6,
    matched: 10,
    error: null,
  },
  {
    id: 'demo-sync-2',
    timestamp: '2026-03-28T19:13:01.000Z',
    window: 30,
    status: 'success',
    found: 90,
    inserted: 22,
    skipped: 31,
    matched: 53,
    error: null,
  },
];
