'use client';

import { useMemo, useState, useTransition } from 'react';
import {
  type StrataNotice,
  type AISummary,
  type Audience,
  type Owner,
  attachmentHasStoredContent,
  isPdfAttachment,
} from '@/lib/definitions';
import type { WithId } from '@/firebase/firestore/use-collection';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
  DialogClose,
} from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Button } from '@/components/ui/button';
import { AlertCircle, Bot, CheckCircle, Download, FileText, Mail, Target, Trash2, Zap } from 'lucide-react';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../ui/table';
import { dispatchGroupNotice, markNoticeAsIgnored, deleteSingleNotice, runAiTriage } from '@/lib/actions';
import { useToast } from '@/hooks/use-toast';
import { getRelevantOwnerProperties, hasOwnerEmail } from '@/lib/owner-matching';


function StatusBadge({ status }: { status: StrataNotice['status'] }) {
  const variant = {
    New: 'secondary',
    Ready: 'default',
    Review: 'destructive',
    Dispatched: 'default',
    Ignored: 'outline',
  }[status] as 'default' | 'secondary' | 'destructive' | 'outline';

  const colorClass = {
    Ready: 'bg-green-500 hover:bg-green-600',
    Dispatched: 'bg-blue-500 hover:bg-blue-600',
    Ignored: 'bg-gray-500 hover:bg-gray-600',
  }[status];

  return (
    <Badge variant={variant} className={colorClass}>
      {status}
    </Badge>
  );
}

function AiSummaryCard({ summary }: { summary: AISummary | null }) {
    if (!summary) {
        return (
            <Card className="border-border/70 bg-white/90 shadow-none">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2"><Bot /> AI Summary</CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground">AI summary has not been generated for this notice yet.</p>
                </CardContent>
            </Card>
        );
    }
    return (
        <Card className="border-border/70 bg-white/90 shadow-none">
            <CardHeader>
                <CardTitle className="flex items-center gap-2"><Bot /> AI Summary</CardTitle>
                <CardDescription>Generated by AI</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-sm">
                <div>
                    <h4 className="font-semibold">What:</h4>
                    <p>{summary.what}</p>
                </div>
                <div>
                    <h4 className="font-semibold">When:</h4>
                    <p>{summary.when}</p>
                </div>
                <div>
                    <h4 className="font-semibold">Impact:</h4>
                    <p>{summary.impact}</p>
                </div>
                <div>
                    <h4 className="font-semibold">Action Required:</h4>
                    <p>{summary.action}</p>
                </div>
            </CardContent>
        </Card>
    );
}

function AudienceCard({ audience }: { audience: Audience | null }) {
    if (!audience) {
        return (
            <Card className="border-border/70 bg-white/90 shadow-none">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2"><Target /> AI Audience Analysis</CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground">AI audience analysis has not been run for this notice yet.</p>
                </CardContent>
            </Card>
        );
    }

    const decisionIcon = {
        BROADCAST: <CheckCircle className="text-green-500" />,
        TARGETED: <Target className="text-blue-500" />,
        DIRECT: <Target className="text-blue-500" />,
        REVIEW: <AlertCircle className="text-yellow-500" />,
    }[audience.decision];
    
    const allHints = [
        ...audience.target_hints.units, 
        ...audience.target_hints.strata_lots, 
        ...audience.target_hints.parking, 
        ...audience.target_hints.locker
    ].filter(Boolean);

    return (
        <Card className="border-border/70 bg-white/90 shadow-none">
            <CardHeader>
                <CardTitle className="flex items-center gap-2"><Target /> AI Audience Analysis</CardTitle>
                <CardDescription>Generated by AI</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-sm">
                 <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Recommendation</span>
                    <Badge variant="outline" className="flex items-center gap-2">
                        {decisionIcon}
                        <span className="font-mono text-xs">{audience.decision}</span>
                    </Badge>
                </div>
                <Separator />
                 <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Confidence</span>
                    <span className="font-medium">{(audience.confidence * 100).toFixed(0)}%</span>
                </div>
                <Separator />
                <div>
                    <h4 className="font-semibold text-muted-foreground mb-2">Evidence from Notice:</h4>
                    <ul className="list-disc pl-5 space-y-1">
                        {audience.evidence.map((e, i) => <li key={i} className="italic text-muted-foreground">"{e}"</li>)}
                    </ul>
                </div>
                 {allHints.length > 0 && (
                    <>
                        <Separator />
                        <div>
                            <h4 className="font-semibold text-muted-foreground mb-2">Targeting Hints:</h4>
                            <div className="flex flex-wrap gap-2">
                                {allHints.map((hint, i) => <Badge key={i} variant="secondary">{hint}</Badge>)}
                            </div>
                        </div>
                    </>
                 )}
            </CardContent>
        </Card>
    );
}

function OwnerMessageCard({ message }: { message: string | null }) {
    if (!message) {
        return (
            <Card className="border-border/70 bg-white/90 shadow-none">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2"><Mail /> Generated Owner Message</CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground">Owner message has not been generated for this notice yet. Run AI Triage from the Inbox.</p>
                </CardContent>
            </Card>
        );
    }
    return (
        <Card className="border-border/70 bg-white/90 shadow-none">
            <CardHeader>
                <CardTitle className="flex items-center gap-2"><Mail /> Generated Owner Message</CardTitle>
                <CardDescription>Generated by AI, ready to be dispatched.</CardDescription>
            </CardHeader>
            <CardContent>
                 <ScrollArea className="h-48">
                    <pre className="whitespace-pre-wrap text-sm font-sans">{message}</pre>
                </ScrollArea>
            </CardContent>
        </Card>
    );
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
}

function AttachmentCard({ notice }: { notice: StrataNotice }) {
    const [previewAttachmentId, setPreviewAttachmentId] = useState<string | null>(null);
    const previewAttachment = notice.attachments.find((attachment) => attachment.id === previewAttachmentId) ?? null;

    if (notice.attachments.length === 0) {
        return (
            <Card className="border-border/70 bg-white/90 shadow-none">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2"><FileText /> Attachments</CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground">No attachments were detected on this notice.</p>
                </CardContent>
            </Card>
        );
    }

    return (
        <>
            <Card className="border-border/70 bg-white/90 shadow-none">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2"><FileText /> Attachments</CardTitle>
                    <CardDescription>PDF files can be previewed here and will be included in dispatch emails.</CardDescription>
                </CardHeader>
                <CardContent className="space-y-3">
                    {notice.attachments.map((attachment) => {
                        const isPdf = isPdfAttachment(attachment);
                        const isStored = attachmentHasStoredContent(attachment);
                        const attachmentUrl = `/api/notices/${encodeURIComponent(notice.id)}/attachments/${encodeURIComponent(attachment.id)}`;

                        return (
                            <div key={attachment.id} className="rounded-lg border p-3">
                                <div className="flex flex-wrap items-start justify-between gap-3">
                                    <div className="space-y-1">
                                        <div className="font-medium">{attachment.filename}</div>
                                        <div className="text-xs text-muted-foreground">
                                            {attachment.contentType} · {formatBytes(attachment.size)}
                                        </div>
                                    </div>
                                    <div className="flex flex-wrap gap-2">
                                        {isPdf && <Badge variant="secondary">PDF</Badge>}
                                        {!isPdf && <Badge variant="outline">Metadata only</Badge>}
                                        {isPdf && !isStored && <Badge variant="destructive">PDF not fetched yet</Badge>}
                                    </div>
                                </div>

                                {isPdf && isStored && (
                                    <div className="mt-3 flex flex-wrap gap-2">
                                        <Button type="button" variant="outline" size="sm" onClick={() => setPreviewAttachmentId(attachment.id)}>
                                            Preview PDF
                                        </Button>
                                        <Button type="button" variant="ghost" size="sm" asChild>
                                            <a href={`${attachmentUrl}?download=1`} target="_blank" rel="noreferrer">
                                                <Download className="mr-2 h-4 w-4" />
                                                Download
                                            </a>
                                        </Button>
                                    </div>
                                )}
                            </div>
                        );
                    })}
                </CardContent>
            </Card>

            <Dialog open={Boolean(previewAttachment)} onOpenChange={(open) => !open && setPreviewAttachmentId(null)}>
                <DialogContent className="max-w-5xl">
                    <DialogHeader>
                        <DialogTitle>{previewAttachment?.filename ?? 'PDF Preview'}</DialogTitle>
                        <DialogDescription>
                            This is the PDF fetched from the original Gmail notice.
                        </DialogDescription>
                    </DialogHeader>
                    {previewAttachment && (
                        <iframe
                            title={previewAttachment.filename}
                            src={`/api/notices/${encodeURIComponent(notice.id)}/attachments/${encodeURIComponent(previewAttachment.id)}`}
                            className="h-[70vh] w-full rounded-md border"
                        />
                    )}
                </DialogContent>
            </Dialog>
        </>
    );
}


function MatchedOwnersCard({
  notice,
  owners,
}: {
  notice: StrataNotice;
  owners: WithId<Owner>[];
}) {
    const planCodes = [notice.planCode, ...notice.allPlanCodes]
      .filter((value): value is string => typeof value === 'string' && value.trim().length > 0)
      .filter((value, index, values) => values.indexOf(value) === index);

    return (
        <Card className="border-border/70 bg-white/90 shadow-none">
            <CardHeader>
                <CardTitle className="flex items-center gap-2"><Target /> Matched Owners</CardTitle>
                <CardDescription>
                    {planCodes.length > 0
                      ? `Matched by strata plan ${planCodes.join(', ')} and any unit hints found in the notice.`
                      : 'No strata plan code was detected yet, so owner matching is unavailable.'}
                </CardDescription>
            </CardHeader>
            <CardContent>
                {owners.length === 0 ? (
                    <p className="text-sm text-muted-foreground">
                        {planCodes.length > 0
                          ? 'No imported owner records match this strata plan yet.'
                          : 'Run Gmail sync and AI triage after you import Buildium owner data to see matches here.'}
                    </p>
                ) : (
                    <ScrollArea className="h-72 pr-4">
                        <div className="space-y-3">
                            {owners.map((owner) => {
                                const relevantProperties = getRelevantOwnerProperties(owner, notice);

                                return (
                                    <div key={owner.id} className="rounded-2xl border border-border/70 bg-muted/15 p-3">
                                        <div className="flex flex-wrap items-start justify-between gap-2">
                                            <div>
                                                <div className="font-medium">{owner.name}</div>
                                                <div className="text-xs text-muted-foreground">
                                                    {owner.email || 'No email on file'}
                                                </div>
                                            </div>
                                            <div className="flex flex-wrap gap-2">
                                                {owner.source === 'buildium' && <Badge variant="secondary">Buildium</Badge>}
                                                {!owner.email && <Badge variant="outline">Match only</Badge>}
                                            </div>
                                        </div>
                                        {relevantProperties.length > 0 && (
                                            <div className="mt-3 flex flex-wrap gap-2">
                                                {relevantProperties.map((property) => (
                                                    <Badge key={`${owner.id}-${property}`} variant="outline">
                                                        {property}
                                                    </Badge>
                                                ))}
                                            </div>
                                        )}
                                    </div>
                                );
                            })}
                        </div>
                    </ScrollArea>
                )}
            </CardContent>
        </Card>
    );
}

function DispatchDialog({ notice, owners, onDispatch, isDispatching }: { notice: StrataNotice; owners: WithId<Owner>[]; onDispatch: () => void; isDispatching: boolean; }) {
    const pdfAttachments = notice.attachments.filter((attachment) => isPdfAttachment(attachment));

    return (
        <DialogContent className="max-w-3xl">
            <DialogHeader>
                <DialogTitle>Confirm Notice Dispatch</DialogTitle>
                <DialogDescription>
                    Review the recommended recipients, the AI-generated message, and any PDF attachments that will be sent out.
                </DialogDescription>
            </DialogHeader>
            
            <div className="grid gap-4 lg:grid-cols-2">
              <div>
                <p className="text-sm font-medium">Message to Owners</p>
                 <div className="rounded-md border p-4 mt-2 min-h-[250px]">
                    {notice.ownerMessage ? (
                      <ScrollArea className="h-64">
                        <pre className="whitespace-pre-wrap text-sm font-sans">{notice.ownerMessage}</pre>
                      </ScrollArea>
                    ) : (
                       <p className="text-muted-foreground">Message not available. Run AI Triage first.</p>
                    )}
                  </div>
              </div>
              <div>
                <p className="text-sm font-medium">
                    Recipients ({owners.length})
                </p>
                <Card className="mt-2 border-border/70 bg-white/90 shadow-none">
                    <CardContent className="p-0">
                        <ScrollArea className="h-72">
                        <Table>
                            <TableHeader>
                                <TableRow>
                                    <TableHead>Name</TableHead>
                                    <TableHead>Email</TableHead>
                                </TableRow>
                            </TableHeader>
                            <TableBody>
                                {owners.map(owner => (
                                    <TableRow key={owner.id}>
                                        <TableCell>{owner.name}</TableCell>
                                        <TableCell>{owner.email}</TableCell>
                                    </TableRow>
                                ))}
                            </TableBody>
                        </Table>
                        </ScrollArea>
                    </CardContent>
                </Card>
                <div className="mt-4">
                    <p className="text-sm font-medium">PDF Attachments ({pdfAttachments.length})</p>
                    <Card className="mt-2 border-border/70 bg-white/90 shadow-none">
                        <CardContent className="space-y-2 p-4 text-sm">
                            {pdfAttachments.length > 0 ? pdfAttachments.map((attachment) => (
                                <div key={attachment.id} className="flex items-center justify-between gap-3 rounded-md border p-2">
                                    <div>
                                        <div className="font-medium">{attachment.filename}</div>
                                        <div className="text-xs text-muted-foreground">{formatBytes(attachment.size)}</div>
                                    </div>
                                    <Badge variant={attachmentHasStoredContent(attachment) ? 'secondary' : 'destructive'}>
                                        {attachmentHasStoredContent(attachment) ? 'Will send' : 'Missing file'}
                                    </Badge>
                                </div>
                            )) : (
                                <p className="text-muted-foreground">No PDF attachments will be included with this dispatch.</p>
                            )}
                        </CardContent>
                    </Card>
                </div>
              </div>
            </div>

            <DialogFooter>
                <DialogClose asChild>
                    <Button variant="outline">Cancel</Button>
                </DialogClose>
                <Button onClick={onDispatch} disabled={isDispatching || !notice.ownerMessage}>
                    {isDispatching ? 'Dispatching...' : `Confirm & Dispatch to ${owners.length} Owners`}
                </Button>
            </DialogFooter>
        </DialogContent>
    );
}


export function NoticeDetailClient({
  notice,
  matchedOwners,
  demoMode = false,
}: {
  notice: StrataNotice;
  matchedOwners: WithId<Owner>[];
  demoMode?: boolean;
}) {
  const [isPending, startTransition] = useTransition();
  const { toast } = useToast();

  const [isDispatchDialogOpen, setIsDispatchDialogOpen] = useState(false);
  const dispatchableOwners = useMemo(
    () =>
      matchedOwners.filter(
        (owner): owner is WithId<Owner> & { email: string } => hasOwnerEmail(owner)
      ),
    [matchedOwners]
  );
  const hasMissingPdfAttachment = useMemo(
    () =>
      notice.attachments.some(
        (attachment) => isPdfAttachment(attachment) && !attachmentHasStoredContent(attachment)
      ),
    [notice.attachments]
  );

  const isActionable = notice.status === 'New' || notice.status === 'Ready' || notice.status === 'Review';

  const handleAiTriage = () => {
    if (demoMode) {
      toast({
        title: 'Demo mode',
        description: 'AI triage is disabled for sample notices.',
      });
      return;
    }
    startTransition(async () => {
      try {
        await runAiTriage(notice.id, notice.content);
        toast({
          title: 'AI Triage Complete',
          description: `Notice has been processed.`,
        });
      } catch (error: any) {
        toast({
          variant: 'destructive',
          title: 'AI Triage Failed',
          description: error.message,
        });
      }
    });
  };

  const handleDispatch = () => {
    if (demoMode) {
      toast({
        title: 'Demo mode',
        description: 'Dispatch is disabled while you are presenting sample data.',
      });
      return;
    }
    if (dispatchableOwners.length === 0) {
      toast({
        variant: 'destructive',
        title: 'No dispatchable recipients',
        description: 'Matched owners were found, but none of them have an email address on file.',
      });
      return;
    }
    if (hasMissingPdfAttachment) {
      toast({
        variant: 'destructive',
        title: 'PDF missing',
        description: 'At least one PDF attachment was detected but not fetched. Re-sync this notice before dispatching.',
      });
      return;
    }
    startTransition(async () => {
      try {
        const result = await dispatchGroupNotice(
          notice.id,
          dispatchableOwners.map((owner) => ({
            id: owner.id,
            name: owner.name,
            email: owner.email,
          }))
        );
        setIsDispatchDialogOpen(false);
        toast({
          title: 'Notice Dispatched',
          description:
            result.pdfAttachments > 0
              ? `Message sent to ${result.recipients} owners with ${result.pdfAttachments} PDF attachment(s).`
              : `Message sent to ${result.recipients} owners.`,
        });
      } catch (error: any) {
        toast({
          variant: 'destructive',
          title: 'Dispatch failed',
          description: error.message || 'An unknown error occurred while sending the notice.',
        });
      }
    });
  };

  const handleIgnore = () => {
    if (demoMode) {
      toast({
        title: 'Demo mode',
        description: 'Status changes are disabled for sample notices.',
      });
      return;
    }
    startTransition(async () => {
      await markNoticeAsIgnored(notice.id);
      toast({ title: 'Notice Ignored' });
    });
  }

  const handleDelete = () => {
    if (demoMode) {
      toast({
        title: 'Demo mode',
        description: 'Delete is disabled while you are presenting sample notices.',
      });
      return;
    }
    startTransition(async () => {
      await deleteSingleNotice(notice.id);
      toast({ title: 'Notice Deleted' });
      // router.push('/inbox') is handled by redirect in server action
    });
  }

  return (
    <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
            {demoMode && (
                <Card className="border-amber-200 bg-amber-50 text-amber-950 shadow-none">
                    <CardContent className="px-5 py-4 text-sm">
                        Demo mode is active. This detail view is safe sample content, so AI triage, dispatch, ignore, and delete are disabled.
                    </CardContent>
                </Card>
            )}
            <OwnerMessageCard message={notice.ownerMessage} />
            <MatchedOwnersCard notice={notice} owners={matchedOwners} />
            <AttachmentCard notice={notice} />
            <Card className="border-border/70 bg-white/90 shadow-none">
                <CardHeader>
                    <div className="flex justify-between items-start">
                        <div>
                            <CardTitle>Original Notice: {notice.subject}</CardTitle>
                            <CardDescription>
                                From: {notice.sender} on <span suppressHydrationWarning>{new Date(notice.receivedAt).toLocaleString()}</span>
                            </CardDescription>
                        </div>
                        <StatusBadge status={notice.status} />
                    </div>
                </CardHeader>
                <CardContent>
                    <ScrollArea className="h-96 w-full rounded-md border p-4">
                        <pre className="whitespace-pre-wrap text-sm">{notice.content}</pre>
                    </ScrollArea>
                </CardContent>
            </Card>
            <div className="flex flex-wrap gap-4">
                 <Button onClick={handleAiTriage} disabled={demoMode || !['New', 'Review'].includes(notice.status) || isPending}>
                    <Zap className="mr-2 h-4 w-4" />
                    Run AI Triage
                </Button>
                <Dialog open={isDispatchDialogOpen} onOpenChange={setIsDispatchDialogOpen}>
                    <DialogTrigger asChild>
                        <Button disabled={demoMode || !isActionable || isPending || !notice.ownerMessage || hasMissingPdfAttachment || dispatchableOwners.length === 0}>Dispatch Notice</Button>
                    </DialogTrigger>
                    <DispatchDialog 
                        notice={notice} 
                        owners={dispatchableOwners}
                        onDispatch={handleDispatch}
                        isDispatching={isPending}
                    />
                </Dialog>
                
                <Button variant="secondary" onClick={handleIgnore} disabled={demoMode || !isActionable || isPending}>Mark as Ignored</Button>
                
                <Dialog>
                    <DialogTrigger asChild>
                         <Button variant="destructive" disabled={demoMode || isPending}><Trash2 className="mr-2 h-4 w-4" /> Delete</Button>
                    </DialogTrigger>
                    <DialogContent>
                        <DialogHeader>
                            <DialogTitle>Are you sure you want to delete this notice?</DialogTitle>
                            <DialogDescription>This action cannot be undone.</DialogDescription>
                        </DialogHeader>
                        <DialogFooter>
                            <DialogClose asChild><Button variant="outline">Cancel</Button></DialogClose>
                            <Button variant="destructive" onClick={handleDelete} disabled={isPending}>
                                {isPending ? 'Deleting...' : 'Confirm Delete'}
                            </Button>
                        </DialogFooter>
                    </DialogContent>
                </Dialog>
            </div>
        </div>

        <div className="space-y-6">
            <AiSummaryCard summary={notice.aiSummary} />
            <AudienceCard audience={notice.audience} />
        </div>
    </div>
  );
}
