'use client';

import type { StrataNotice, AISummary, Audience } from '@/lib/definitions';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Button } from '@/components/ui/button';
import { AlertCircle, Bot, CheckCircle, Target } from 'lucide-react';

function StatusBadge({ status }: { status: StrataNotice['status'] }) {
  const variant = {
    New: 'secondary',
    Ready: 'default',
    Review: 'destructive',
    Dispatched: 'default',
    Ignored: 'outline',
  }[status] as 'default' | 'secondary' | 'destructive' | 'outline';

  const colorClass = status === 'Ready' ? 'bg-green-500 hover:bg-green-600' : '';

  return (
    <Badge variant={variant} className={colorClass}>
      {status}
    </Badge>
  );
}

function AiSummaryCard({ summary }: { summary: AISummary | null }) {
    if (!summary) {
        return (
            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-2"><Bot /> AI Summary</CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground">AI summary has not been generated for this notice yet.</p>
                </CardContent>
            </Card>
        );
    }
    return (
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2"><Bot /> AI Summary</CardTitle>
                <CardDescription>Generated by AI</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-sm">
                <div>
                    <h4 className="font-semibold">What:</h4>
                    <p>{summary.what}</p>
                </div>
                <div>
                    <h4 className="font-semibold">When:</h4>
                    <p>{summary.when}</p>
                </div>
                <div>
                    <h4 className="font-semibold">Impact:</h4>
                    <p>{summary.impact}</p>
                </div>
                <div>
                    <h4 className="font-semibold">Action Required:</h4>
                    <p>{summary.action}</p>
                </div>
            </CardContent>
        </Card>
    );
}

function AudienceCard({ audience }: { audience: Audience | null }) {
    if (!audience) {
        return (
            <Card>
                <CardHeader>
                    <CardTitle className="flex items-center gap-2"><Target /> AI Audience Analysis</CardTitle>
                </CardHeader>
                <CardContent>
                    <p className="text-muted-foreground">AI audience analysis has not been run for this notice yet.</p>
                </CardContent>
            </Card>
        );
    }

    const decisionIcon = {
        BROADCAST: <CheckCircle className="text-green-500" />,
        TARGETED: <Target className="text-blue-500" />,
        DIRECT: <Target className="text-blue-500" />,
        REVIEW: <AlertCircle className="text-yellow-500" />,
    }[audience.decision];
    
    const allHints = [
        ...audience.target_hints.units, 
        ...audience.target_hints.strata_lots, 
        ...audience.target_hints.parking, 
        ...audience.target_hints.locker
    ];

    return (
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2"><Target /> AI Audience Analysis</CardTitle>
                <CardDescription>Generated by AI</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-sm">
                 <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Recommendation</span>
                    <Badge variant="outline" className="flex items-center gap-2">
                        {decisionIcon}
                        <span className="font-mono text-xs">{audience.decision}</span>
                    </Badge>
                </div>
                <Separator />
                 <div className="flex items-center justify-between">
                    <span className="text-muted-foreground">Confidence</span>
                    <span className="font-medium">{(audience.confidence * 100).toFixed(0)}%</span>
                </div>
                <Separator />
                <div>
                    <h4 className="font-semibold text-muted-foreground mb-2">Evidence from Notice:</h4>
                    <ul className="list-disc pl-5 space-y-1">
                        {audience.evidence.map((e, i) => <li key={i} className="italic text-muted-foreground">"{e}"</li>)}
                    </ul>
                </div>
                 {allHints.length > 0 && (
                    <>
                        <Separator />
                        <div>
                            <h4 className="font-semibold text-muted-foreground mb-2">Targeting Hints:</h4>
                            <div className="flex flex-wrap gap-2">
                                {allHints.map((hint, i) => <Badge key={i} variant="secondary">{hint}</Badge>)}
                            </div>
                        </div>
                    </>
                 )}
            </CardContent>
        </Card>
    );
}

export function NoticeDetailClient({ notice }: { notice: StrataNotice }) {
  return (
    <div className="grid gap-6 lg:grid-cols-3">
        <div className="lg:col-span-2 space-y-6">
            <Card>
                <CardHeader>
                    <div className="flex justify-between items-start">
                        <div>
                            <CardTitle>{notice.subject}</CardTitle>
                            <CardDescription>
                                From: {notice.sender} on <span suppressHydrationWarning>{new Date(notice.receivedAt).toLocaleString()}</span>
                            </CardDescription>
                        </div>
                        <StatusBadge status={notice.status} />
                    </div>
                </CardHeader>
                <CardContent>
                    <ScrollArea className="h-96 w-full rounded-md border p-4">
                        <pre className="whitespace-pre-wrap text-sm">{notice.content}</pre>
                    </ScrollArea>
                </CardContent>
            </Card>
            <div className="flex gap-4">
                <Button>Dispatch Notice</Button>
                <Button variant="secondary">Mark as Ignored</Button>
                <Button variant="destructive">Delete</Button>
            </div>
        </div>

        <div className="space-y-6">
            <AiSummaryCard summary={notice.aiSummary} />
            <AudienceCard audience={notice.audience} />
        </div>
    </div>
  );
}